#- name: Source bashrc
#  ansible.builtin.shell: ". {{ home }}/.bashrc"
- name: Install node and set version
  ansible.builtin.shell:
    cmd: bash -c "source {{ home }}/.nvm/nvm.sh && nvm install stable && nvm alias default stable && nvm use stable"
    creates: "{{ home }}/.nvm/alias"
- name: Install yarn
  ansible.builtin.shell:
    cmd: npm install -g yarn
    creates: "{{ lookup('env', 'NVM_BIN') }}/yarn"
- name: Install pm2
  ansible.builtin.shell:
    cmd: npm install -g pm2
    creates: "{{ lookup('env', 'NVM_BIN') }}/pm2"
- name: Install near-cli
  ansible.builtin.shell: 
    cmd: npm install -g near-cli
    creates: "{{ lookup('env', 'NVM_BIN') }}/near"